# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Next.js app to Azure Web App - algohire-ai-notes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared packages
        run: pnpm --filter @repo/shared build

      - name: Build Next.js app
        run: pnpm --filter web build

      - name: Prepare Next.js deployment
        run: |
          # Create deployment directory
          mkdir -p deploy
          
          # Copy Next.js build output
          cp -r apps/web/.next deploy/
          cp -r apps/web/public deploy/
          cp apps/web/next.config.js deploy/ 2>/dev/null || echo "No next.config.js found"
          
          # Create package.json using echo
          echo '{
            "name": "algohire-nextjs-app",
            "version": "1.0.0",
            "scripts": {
              "start": "next start",
              "build": "next build"
            },
            "dependencies": {
              "@hookform/resolvers": "^3.10.0",
              "@radix-ui/react-alert-dialog": "^1.1.14",
              "@radix-ui/react-avatar": "^1.1.10",
              "@radix-ui/react-dialog": "^1.1.14",
              "@radix-ui/react-dropdown-menu": "^2.1.15",
              "@radix-ui/react-label": "^2.1.7",
              "@radix-ui/react-progress": "^1.1.7",
              "@radix-ui/react-separator": "^1.1.7",
              "@radix-ui/react-slot": "^1.2.3",
              "@radix-ui/react-tabs": "^1.1.12",
              "@radix-ui/react-toast": "^1.2.14",
              "@tanstack/react-query": "^5.80.10",
              "@tanstack/react-query-devtools": "^5.80.10",
              "axios": "^1.10.0",
              "class-variance-authority": "^0.7.1",
              "clsx": "^2.1.1",
              "firebase": "^10.14.1",
              "framer-motion": "^12.18.1",
              "ioredis": "^5.6.1",
              "lucide-react": "^0.263.1",
              "motion": "^12.18.1",
              "next": "^14.2.30",
              "react": "^18.3.1",
              "react-dom": "^18.3.1",
              "react-hook-form": "^7.58.1",
              "socket.io-client": "^4.8.1",
              "sonner": "^1.7.4",
              "tailwind-merge": "^2.6.0",
              "zod": "^3.25.67"
            }
          }' > deploy/package.json
          
          # Copy shared package if it exists
          if [ -d "packages/shared/dist" ]; then
            mkdir -p deploy/node_modules/@repo
            cp -r packages/shared deploy/node_modules/@repo/shared
          fi
          
          echo "Next.js deployment prepared successfully"
          ls -la deploy/

      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../nextjs-release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: nextjs-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip nextjs-release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4FD459436E07453A9569D1797D91859E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_93FF2D2E9049499D92A61252C3EE010A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_28A0D1C68F2549EEB11F5A1238A5E0B4 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'algohire-ai-notes'
          slot-name: 'Production'
          package: .